version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-usuarios
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cine_usuarios_db
      MYSQL_USER: cine_user
      MYSQL_PASSWORD: cine_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  usuario-service:
    build: .
    container_name: microservice-usuarios
    environment:
      DATABASE_URL: mysql+pymysql://cine_user:cine_password@mysql-db:3306/cine_usuarios_db
      JWT_SECRET: clave-secreta-usuarios
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db

volumes:
  mysql_data: